name: Build db files
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 4"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Set variables
        run: |
          echo "RELEASE_NAME=$(date +%Y-%m-%d)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y-%m-%d)" >> $GITHUB_ENV
        shell: bash

      - name: Build files
        run: |
          go run .

      - name: Generate sha256 hash
        run: |
          sha256sum rules/az.srs > rules/az.srs.sha256sum
          sha256sum rules/af.srs > rules/af.srs.sha256sum

      - name: Release and upload assets
        run: |
          gh release create ${{ env.TAG_NAME }} --generate-notes --latest --title ${{ env.RELEASE_NAME }} rules/*.srs.sha256sum rules/*.srs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
